/*************************************************************************

    xtal.h

    Documentation and consistent naming for known existing crystals.

    Copyright Nicola Salmoria and the MAME Team.
    Visit http://mamedev.org for licensing and usage restrictions.

***************************************************************************

    PCB Crystal Reference
    ----------------------
       _____     ________
       |16 |    |o       |
       |MHZ|    |16.0MHZ |
       |___|    |________|
       |   |

    There is a finite list of _manufactured_ crystals. This file aims
    to document all of the known speeds that crystals were available in.
    Feel free to add to the list if you find another speed crystal on
    a PCB, but please DON'T GUESS!

    Remember that some very high frequencies (typically above 100MHz) are
    generated by a frequency multiplying IC from a lower frequency
    crystal.

    This is intended as a reference of existing parts to prevent incorrect
    clock speed measurements with digital frequency counters being used
    in drivers. When measuring clocks, remember that most parts have a
    tolerance so be sure to reference existing parts only and not just
    accept direct readings as 100% true.

    (Thanks to Guru for starting this documentation.)

**************************************************************************/


enum
{
/*
	Name			= Frequency		Examples
	----------------        ------------	     ------------------------------------------------------------ */

	XTAL_375KHz		= 375000,		/* MSM5205 for some bootleg CPS1 */
	XTAL_455kHz		= 455000,		/* Used on Gladiator h/w */
	XTAL_1MHz   		= 1000000,		/* Used to drive OKI M6295 chips */
	XTAL_3_579545MHz	= 3579545,		/* NTSC color subcarrier, extremely common, used on 100's of PCBs */
	XTAL_3_727625MHz	= 3727625,		/* Z80 for some bootleg CPS1 */
	XTAL_4MHz   		= 4000000,		/* Z80 for some CPS1 board */
	XTAL_4_41MHz		= 4410000,		/* Pioneer PR-8210 ldplayer */
	XTAL_5MHz   		= 5000000,		/* Mutant Night */
	XTAL_6MHz   		= 6000000,		/* American Poker II */
	XTAL_7_15909MHz		= 7159090,		/* V30 for M92 board */
	XTAL_8MHz   		= 8000000,		/* Extremely common, used on 100's of PCBs */
	XTAL_9MHz		= 9000000,		/* V33 for M92 board */
	XTAL_10MHz  		= 10000000,
	XTAL_11MHz		= 11000000,		/* Mario I8039 sound */
	XTAL_12MHz  		= 12000000,		/* Extremely common, used on 100's of PCBs */
	XTAL_14_31818MHz	= 14318180,		/* Extremely common, used on 100's of PCBs */
	XTAL_16MHz  		= 16000000,		/* Extremely common, used on 100's of PCBs */
	XTAL_26_66666MHz	= 26666660		/* Irem M92 but most use 27MHz */
};
